### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by ErickNavarroD** [stat545ubc-2022/Tri_Van_Mini-Data-Analysis-1and2#1]
Hi!
Amazing work! It is clear that you understand very clearly all the concepts that we have seen during the class. All of your steps were very clear and the reasons you had to conduct each steps of the analysis were very thought. Congratulations! The only issue I saw was in the exploration task, where you did not use a dplyr function for it (you were supposed to use glimpse or something similar)
Just as a comment, I would only recommend you not to use density plots to compare the relationship between 2 or more variables, since you are plotting a density and that makes it sometimes tricky to compare the actual frequency of different categories. Since the area of each distribution is 1, you can have weird conclusions if you just want to look at how the frequency changes in different distributions, which is where I think you were going.

**Comment by Tri-Van** [comment]
@ErickNavarroD Thank you for your feeback!
In regarding to the first part, i believe I did use the "glimpse" function. Specifically, I used class(), head(), summary(), head() and glimpse() to explore the steam_games, apt_buildings and building_permits data set.

I will keep the second part in mind for the second milestones!

**Comment by ErickNavarroD** [comment]
You're right! Sorry, I missed those lines. I will update your grade (:
